### ISSUE TITLE
qemu: failed to restart after kernel taint

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/runltp-ng#9]
```
$ ./runltp-ng --sut qemu:image=debian-10.3.img --run-suite syscalls
...
setsockopt09: fail | tained  (6m 14s)
Restarting SUT: qemu

Disconnecting from SUT: qemu
Error: Can't read return code from reply " stty -echo; stty cols 1024\nexport PS1=''; echo $?-fyJq3vEy16"
```

**Comment by metan-ucw** [comment]
[debug.log](https://github.com/linux-test-project/runltp-ng/files/10435298/debug.log)

**Comment by acerv** [comment]
It seems like qemu rebooted correctly many times during syscalls runtest execution, but the last one caused the following error:
```

2023-01-17 11:53:32,198 - ltp.dispatcher:312 - INFO - Rebooting SUT
2023-01-17 11:53:32,198 - ltp.qemu:428 - INFO - Shutting down virtual machine
2023-01-17 11:53:32,198 - ltp.qemu:435 - INFO - Killing virtual machine process
2023-01-17 11:53:32,377 - ltp.qemu:471 - INFO - Starting virtual machine
2023-01-17 11:53:32,377 - ltp.qemu:472 - DEBUG - qemu-system-x86_64 -enable-kvm -display none -m 2G -smp 2 -device virtio-rng-pci -drive if=virtio,cache=unsafe,file=debian-10.3.img -chardev stdio,id=tty,logfile=/tmp/runltp.metan/tmpr7bvbuxz/ttyS0-4898.log -serial chardev:tty -serial chardev:transport -chardev file,id=transport,path=/tmp/runltp.metan/tmpr7bvbuxz/transport-4898
2023-01-17 11:53:44,597 - ltp.qemu:308 - DEBUG - Execute (timeout 5.000000): "export PS1=''"
2023-01-17 11:53:44,597 - ltp.qemu:316 - INFO - Sending "export PS1='';echo $?-fyJq3vEy16\n"
2023-01-17 11:53:44,599 - ltp.qemu:360 - INFO - Shutting down virtual machine
2023-01-17 11:53:44,599 - ltp.qemu:404 - INFO - Killing virtual machine process
2023-01-17 11:53:44,667 - ltp.session:336 - ERROR - Can't read return code from reply " stty -echo; stty cols 1024\nexport PS1=''; echo $?-fyJq3vEy16"
Traceback (most recent call last):
  File "/home/metan/Work/acer/runltp-ng/ltp/qemu.py", line 503, in communicate
    _, retcode, _ = self._exec("export PS1=''", 5, None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/metan/Work/acer/runltp-ng/ltp/qemu.py", line 331, in _exec
    raise SUTError(
ltp.sut.SUTError: Can't read return code from reply " stty -echo; stty cols 1024\nexport PS1=''; echo $?-fyJq3vEy16"
```
